# Main Database
spring:
  datasource:
    url: jdbc:h2:file:D:/H2DB/H2_DB_ProjectFiles
    driverClassName: org.h2.Driver
    username: sa
    password: andreas
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # create-drop
      ddl-auto: none

  # H2 Console http://localhost:8080/h2-project
  h2:
    console:
      enabled: true
      path: /h2-project

    # Strategy for model naming
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
